# Evaluation of Screening metrics

In [1]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from pathlib import Path
from scipy.stats import spearmanr, pearsonr

In [2]:
#loading data
df = pd.read_parquet("../runs/dgp0/seed_42/baseline/screen/screen_L18.parquet")
df.head()

,market_id,n_windows,mean_score,sd_score,pct_above_tau95,pct_above_tau99,longest_run_tau95,max_score,true_pct_cartel_windows,true_pct_pure_cartel_windows,true_mean_share_K,true_max_share_K,true_longest_cartel_run,structural_intensity,effective_structural_intensity
0,0,163,0.986324,1.663924,0.134969,0.098160,21,6.898086,0.159509,0.098160,0.158487,1.0,26,1.220344,0.193408
1,1,163,0.173206,0.915087,0.018405,0.000000,2,2.445173,0.503067,0.472393,0.500000,1.0,82,0.923597,0.461799
2,2,163,0.780515,0.568437,0.055215,0.000000,5,2.676170,0.877301,0.815951,0.883436,1.0,105,1.039488,0.918321
3,3,163,-0.431864,1.299108,0.000000,0.000000,0,1.457906,0.496933,0.374233,0.502045,1.0,67,1.527707,0.766978
4,4,163,1.688749,1.285166,0.325153,0.110429,33,5.663607,0.116564,0.085890,0.119632,1.0,19,0.827842,0.099036

In [26]:
cols = [
    "mean_score",
    "pct_above_tau95",
    "pct_above_tau99",
    "longest_run_tau95",
    "sd_score",
    "max_score",
    "true_pct_cartel_windows",
    "true_pct_pure_cartel_windows",
    "true_mean_share_K",
    "true_longest_cartel_run",
    "true_max_share_K",
    "structural_intensity", 
    "effective_structural_intensity"
]

cor = df[cols].corr()

fig = px.imshow(
    cor,
    text_auto=True,           
    color_continuous_scale='Viridis', 
    title='Correlation Matrix'
)

fig.show()

In [15]:
for col in cols:
    spear_cor = coef, p_value = spearmanr(df[col], df["effective_structural_intensity"])
    print(f"Spearman correlation for {col}: {coef:.3f}, p-value: {p_value:.3f}")

Spearman correlation for mean_score: 0.427, p-value: 0.000
Spearman correlation for pct_above_tau95: 0.416, p-value: 0.000
Spearman correlation for pct_above_tau99: 0.320, p-value: 0.000
Spearman correlation for longest_run_tau95: 0.398, p-value: 0.000
Spearman correlation for sd_score: 0.227, p-value: 0.001
Spearman correlation for max_score: 0.356, p-value: 0.000
Spearman correlation for true_pct_cartel_windows: 0.963, p-value: 0.000
Spearman correlation for true_pct_pure_cartel_windows: 0.954, p-value: 0.000
Spearman correlation for true_mean_share_K: 0.964, p-value: 0.000
Spearman correlation for true_longest_cartel_run: 0.923, p-value: 0.000
Spearman correlation for structural_intensity: 0.157, p-value: 0.026
Spearman correlation for effective_structural_intensity: 1.000, p-value: 0.000

In [23]:
for col in cols:
    spear_cor = coef, p_value = spearmanr(df[col], df["true_mean_share_K"])
    print(f"Spearman correlation for {col}: {coef:.3f}, p-value: {p_value:.3f}")

Spearman correlation for mean_score: 0.413, p-value: 0.000
Spearman correlation for pct_above_tau95: 0.381, p-value: 0.000
Spearman correlation for pct_above_tau99: 0.281, p-value: 0.000
Spearman correlation for longest_run_tau95: 0.358, p-value: 0.000
Spearman correlation for sd_score: 0.141, p-value: 0.046
Spearman correlation for max_score: 0.320, p-value: 0.000
Spearman correlation for true_pct_cartel_windows: 0.998, p-value: 0.000
Spearman correlation for true_pct_pure_cartel_windows: 0.990, p-value: 0.000
Spearman correlation for true_mean_share_K: 1.000, p-value: 0.000
Spearman correlation for true_longest_cartel_run: 0.958, p-value: 0.000
Spearman correlation for structural_intensity: -0.048, p-value: 0.498
Spearman correlation for effective_structural_intensity: 0.964, p-value: 0.000

In [27]:
for col in cols:
    spear_cor = coef, p_value = spearmanr(df[col], df["true_max_share_K"])
    print(f"Spearman correlation for {col}: {coef:.3f}, p-value: {p_value:.3f}")

Spearman correlation for mean_score: 0.354, p-value: 0.000
Spearman correlation for pct_above_tau95: 0.363, p-value: 0.000
Spearman correlation for pct_above_tau99: 0.290, p-value: 0.000
Spearman correlation for longest_run_tau95: 0.369, p-value: 0.000
Spearman correlation for sd_score: 0.256, p-value: 0.000
Spearman correlation for max_score: 0.378, p-value: 0.000
Spearman correlation for true_pct_cartel_windows: 0.663, p-value: 0.000
Spearman correlation for true_pct_pure_cartel_windows: 0.667, p-value: 0.000
Spearman correlation for true_mean_share_K: 0.666, p-value: 0.000
Spearman correlation for true_longest_cartel_run: 0.662, p-value: 0.000
Spearman correlation for true_max_share_K: 1.000, p-value: 0.000
Spearman correlation for structural_intensity: 0.066, p-value: 0.351
Spearman correlation for effective_structural_intensity: 0.667, p-value: 0.000

In [30]:
for col in cols:
    spear_cor = coef, p_value = spearmanr(df[col], df["true_longest_cartel_run"])
    print(f"Spearman correlation for {col}: {coef:.3f}, p-value: {p_value:.3f}")

Spearman correlation for mean_score: 0.396, p-value: 0.000
Spearman correlation for pct_above_tau95: 0.371, p-value: 0.000
Spearman correlation for pct_above_tau99: 0.273, p-value: 0.000
Spearman correlation for longest_run_tau95: 0.355, p-value: 0.000
Spearman correlation for sd_score: 0.156, p-value: 0.028
Spearman correlation for max_score: 0.318, p-value: 0.000
Spearman correlation for true_pct_cartel_windows: 0.961, p-value: 0.000
Spearman correlation for true_pct_pure_cartel_windows: 0.973, p-value: 0.000
Spearman correlation for true_mean_share_K: 0.958, p-value: 0.000
Spearman correlation for true_longest_cartel_run: 1.000, p-value: 0.000
Spearman correlation for true_max_share_K: 0.662, p-value: 0.000
Spearman correlation for structural_intensity: -0.044, p-value: 0.534
Spearman correlation for effective_structural_intensity: 0.923, p-value: 0.000

In [29]:
fig = px.scatter(
    df,
    x="effective_structural_intensity",
    y="mean_score",
    hover_data=["market_id"],
    title="Market Mean Conduct Score vs Effective Structural Intensity",
    template="plotly_white", 
    trendline="ols", 
    trendline_color_override="orange"
)
fig.show()

In [28]:
fig = px.scatter(
    df,
    x="effective_structural_intensity",
    y="pct_above_tau95",
    hover_data=["market_id"],
    title="Share of Suspicious Windows vs Effective Structural intensity ",
    template="plotly_white", 
    trendline="ols",
    trendline_color_override="orange"
)
fig.show()

In [20]:
market_eval = df.sort_values("mean_score", ascending=False).copy()

market_eval[
        [
            "market_id",
            "mean_score",
            "pct_above_tau95",
            "longest_run_tau95",
            "true_mean_share_K",
            "true_longest_cartel_run",
            "effective_structural_intensity", 
            "structural_intensity"
        ]
    ].head(10)

,market_id,mean_score,pct_above_tau95,longest_run_tau95,true_mean_share_K,true_longest_cartel_run,effective_structural_intensity,structural_intensity
90,90,4.774092,0.539877,88,0.546012,88,0.928393,1.700316
184,184,4.323030,0.809816,98,0.491138,79,0.586604,1.194376
166,166,4.196030,0.828221,64,0.228016,35,0.269755,1.183053
26,26,3.936028,0.619632,76,0.457055,74,0.769962,1.684615
75,75,3.827194,0.601227,98,0.631902,105,0.939609,1.486953
25,25,3.768656,0.705521,54,0.434560,38,0.537950,1.237917
186,186,3.746881,0.650307,34,0.579755,42,0.693261,1.195783
56,56,3.474385,0.680982,58,0.395706,64,0.530778,1.341347
79,79,3.367580,0.723926,85,0.644172,107,0.820279,1.273386
42,42,3.343216,0.723926,68,0.717791,118,0.914588,1.274170

In [8]:
fig = px.scatter(
    df,
    x="true_longest_cartel_run",
    y="longest_run_tau95",
    hover_data=["market_id"],
    title="Share of Suspicious Windows vs True Mean Cartel Exposure",
    template="plotly_white", 
    trendline="ols",
    trendline_color_override="orange"
)
fig.show()

In [32]:
market_eval = df.sort_values("true_mean_share_K", ascending=False).copy()

market_eval[
        [
             "market_id",
            "mean_score",
            "pct_above_tau95",
            "longest_run_tau95",
            "true_mean_share_K",
            "true_longest_cartel_run",
            "effective_structural_intensity", 
            "structural_intensity"
        ]
    ].head(10)

,market_id,mean_score,pct_above_tau95,longest_run_tau95,true_mean_share_K,true_longest_cartel_run,effective_structural_intensity,structural_intensity
144,144,1.419253,0.159509,11,1.000000,163,1.386193,1.386193
100,100,0.828758,0.000000,0,1.000000,163,1.280582,1.280582
198,198,1.680434,0.312883,27,0.997955,163,1.362160,1.364952
45,45,1.237557,0.110429,18,0.996592,163,0.724926,0.727405
139,139,1.624217,0.226994,20,0.990457,163,1.331967,1.344801
181,181,1.965473,0.417178,17,0.981254,161,0.948953,0.967081
13,13,1.421920,0.122699,20,0.973415,161,1.371459,1.408915
87,87,2.523642,0.484663,33,0.968303,163,1.322969,1.366276
134,134,1.022221,0.067485,11,0.957055,163,1.322606,1.381954
65,65,1.937040,0.398773,23,0.953647,157,0.971774,1.019008

## Structural intensity

In [21]:
r_p, p_p = pearsonr(market_eval["mean_score"], market_eval["effective_structural_intensity"])
r_s, p_s = spearmanr(market_eval["mean_score"], market_eval["effective_structural_intensity"])

print("Pearson :", r_p, p_p)
print("Spearman:", r_s, p_s)

Pearson : 0.385020665935511 1.8081788416087933e-08
Spearman: 0.427188376638311 2.818504583944424e-10

In [34]:
fig = px.scatter(
    market_eval,
    x="true_mean_share_K",
    y="mean_score",
    hover_data=["market_id"],
    trendline="ols",
    trendline_color_override="orange", 
    title="Mean Conduct Score vs True cartel exposure",
    template="plotly_white"
)
fig.show()